### ISSUE TITLE
Make the TV refresh when we push

### ISSUE THREAD

**Issue by jgorset** [hyperoslo/tv#1]
It would be great if the TV refreshed automatically when we push to the `gh-pages` branch somehow.

**Comment by zenangst** [comment]
:100:

**Comment by zenangst** [comment]
Webhooks?

**Comment by jgorset** [comment]
Yeah, probably webhooks.

**Comment by jgorset** [comment]
I hate myself for saying this, but I think an `iframe` is the right way to go here…

**Comment by jgorset** [comment]
Webhooks require something to `POST` to, which we don't really have now that it's hosted off of the GitHub repository. If we just poll GitHub's API for new commits to the `gh-pages` branch, though, it can intelligently refresh when something's changed.

**Comment by jgorset** [comment]
I made this in https://github.com/hyperoslo/tv/commit/3c49decf35b5e1549ff9a91867c8b7f51a364ac0!
